[project]
name = "frontrun-search"
authors = ["anonymouse"]
description = "A decentralized marketplace for detecting and preventing blockchain transaction frontrunning"
telemetry = false
requirements = []
[contracts.frontrun-search]
path = "contracts/frontrun-search.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
